#!/bin/bash
set -e
if [ $# -eq 0 ]; then
    echo "fmriprep_wrapper loads the proper python environment and executes fmriprep. It expects a full call to fmriprep."
    echo "Example: fmriprep_wrapper --n_cpus 8 --verbose --output-space template --write-graph --participant_label 040 --use-aroma -w work bids output participant"
    exit 1
fi

command -v deactivate >/dev/null 2>&1 && deactivate #exit existing virtual environment if active
module unload python #make sure no system python modules are loaded

#activate fmriprep python environment
source /gpfs/group/mnh5174/default/lab_resources/fmriprep_python/bin/activate

fmriprep "$@" #pass all arguments forward
